global using Academic.API.Exceptions;
global using Academic.Application.Mapper.Configuration;
global using Microsoft.OpenApi.Models;
global using Academic.Infrastructure.Data;
global using Microsoft.EntityFrameworkCore;
global using Academic.Core.Entities;
global using FluentValidation.AspNetCore;
global using Microsoft.AspNetCore.Identity;
global using Academic.Application.Authentication;